---
title: 'Next.js 14 App router Next-auth 컴파일시 authOption 오류'
desc: ''
thumbnail: ''
tags:
  - 코드
date: 2024-06-04 15:52:00
---

### 개요

팀프로젝트를 Next.js 14 App route의 사용하게 되었고 Next-auth을 통해 로그인을 구현하고 빌드를 할 때 해당 오류가 나타는 것을 확인했습니다.

```
.next/types/app/api/auth/[...nextauth]/route.ts:8:13
Type error: Type 'OmitWithTag<typeof import("D:/\uC791\uC5C5/\uD504\uB85C\uC81D\uD2B8 \uAD00\uB828/gugumo_frontend/src/app/api/auth/[...nextauth]/route"), "GET" | "POST" | "HEAD" | "OPTIONS" | "PUT" | "DELETE" | "PATCH" | "config" | "generateStaticParams" | ... 6 more ... | "maxDuration", "">' does not satisfy the constraint '{ [x: string]: never; }'.
  Property 'authOptions' is incompatible with index signature.
    Type 'AuthOptions' is not assignable to type 'never'.

   6 |
   7 | // Check that the entry is a valid entry
>  8 | checkFields<Diff<{
     |             ^
   9 |   GET?: Function
  10 |   HEAD?: Function
  11 |   OPTIONS?: Function
```

해당 오류를 해결하기 위해 작성하게 되었습니다.

### 해결방안

\[...nextauth\]/route.ts 의 코드를 보시면

```
import axios from "axios";
import NextAuth, { NextAuthOptions } from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials"

export const authOptions : NextAuthOptions = {
    providers : [
        CredentialsProvider({
            name : "Credentials",
            credentials : {
                username: { type: "email", placeholder: "이메일을 입력해주세요." },
                password: { type: "password",placeholder: "비밀번호를 입력해주세요." }
            },
            async authorize(credentials) : Promise<any> {
                ...
            }
        })
    ],
    callbacks : {
        ...
    }
}

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST }
```

authOptions을 따로 만들어서 NextAuth로 보내주고 있는데  
typescript에서 authOptions에게 export을 넣어서 생기는 오류입니다.

nextJs 13.4+ 에서 route.ts는 route hanlder을 이용하고 이 안에서 export 해서 내보내려고 했기 때문에 발생하는 오류입니다.

해당 오류는 authOptions을 따로 파일을 만들어서 import 해주면 해결할 수 있는 간단한 트러블이었습니다.

**/lib/authOptions.ts**

```
import axios from "axios";
import { NextAuthOptions } from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials"

export const authOptions : NextAuthOptions = {
    providers : [
        CredentialsProvider({
            name : "Credentials",
            credentials : {
                username: { type: "email", placeholder: "이메일을 입력해주세요." },
                password: { type: "password",placeholder: "비밀번호를 입력해주세요." }
            },
            async authorize(credentials) : Promise<any> {
                ...
            }
        })
    ],
    secret : process.env.NEXTAUTH_SECRET,
    callbacks : {
        ...
    }
}
```

/app/api/\[...nextauth\]/route.ts

```
import { authOptions } from "@lib/authOptions";
import NextAuth from "next-auth"

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST }
```

이렇게 하면 문제를 해결할 수 있었습니다.

### 참고자료

[https://stackoverflow.com/questions/76388994/next-js-13-4-and-nextauth-type-error-authoptions-is-not-assignable-to-type-n](https://stackoverflow.com/questions/76388994/next-js-13-4-and-nextauth-type-error-authoptions-is-not-assignable-to-type-n)